Notes on the Testing and Verification Protocol
* TESTS
** Ginger 
   physical structure of the harness (it must support the eye, keep it
   safe, rotate cleanly, fit into frame, etc etc)

*** Tweezer support and eyeballs
    + Importance :: (vital for operation ~ interesting to know): good to know that the tweezers are holding eyeball at right amount of force so that the eyeball will not slip during spinning/scanning process and significantly affect data. 
    + Purpose and background :: The reverse action tweezers have been
         modified to fit into the physical top cap of the piece. This
         tests whether the cap has been made properly, that is,
         whether the tweezers are still functional within the cap (where in they won't break optic nerve (by gripping with too much force) or release optic nerve (and eyeball) during scanning (by griping with too little force)
    + Functionality :: meets speed EDS; essentially tests the force of tweezer upon eyeball

**** Protocol Details
    1. Use tweezers to hold the eyeball at a set force
    2. Spin the motor at constant velocity we are choosing to use for operation
    3. See whether optic nerve breaks or slips
    4. See whether eyeball wobbles too much using that set amount of force
--> notes: Is there any way we can measure the force of the tweezers upon the eyeball using some kind of load cell or equivalent???
    5. Repeat with different amount of force.
**** Results
     + Test Metrics :: the range of force at which tweezers hold eyeball without slippage and breaking; the position of the eyeball during the tests
     + Possible Results :: 
1. the force which we hold eyeball causes optic nerve slippage or breakage = failure
2. moderate failure - force does not cause slippage/breakage but does make eyeball "wobble" too much and significantly affects position data (or scanning)
3. success = force causes no slippage/breakage, any "wobbling" that occurs does not significantly affect position data

*** Tube/caps/silicon
    + Importance :: do the caps and silicon seal the tube
    + Purpose/background :: are the caps going to fall off with high
         velocity motor spin?
    + Functionality :: same as purpose?
**** Protocol
     1. spin motor and incrementally increase speed
     2. do caps fall off? (does Si seal the caps to the tube as it
        should?)
**** Results
     + Test Metrics :: not sure of any numbers - range of distance
                       that caps detach from the tube
     + Possible test results :: does cap completely detach from tube
          or just a little bit at high-velocity motor speed (or lower
          motor speeds that we use to perate the device) Notes: this isn't that important. 

*** Name of test: fluid inside tube
    + Importance :: Does the polymer affect the scanning? (Will it cause light diffusion to the point of damaging our measurement as Joe states?)
    + Purpose/background :: The eye will be fixed in polymer solution, so
         how much does sol'n affect the scan? can eyeball be detected
         effectively or does solution completely block transmittance
         of light? 
    + Functionality :: Resolution EDS
**** Protocol
     1. fill fluid in (optic) tube, fix eyeball in center using tweezers
     2. scan eyeball by rotating at constant velocity and collect position data
     3. perform 3D reconstruction upon data and see resulting shape/dimensions
     4. repeat using control - an (optic) tube with no fluid
     5. We could possibly use different polymer compositions - our current fluid is 10% methyl cellulose to water; we could also try 5% MC/H2O or Karo corn syrup

**** Results
     + Test Metrics :: the scanning/position data of each case; the 3D reconstruction/calculated dimensions of each case
     + Possible test results :: 
      failure: exp. and control position/reconstruction data differs significantly (eyeball cannot be detected at all because solution
          is too opaque)
      success: exp. and control position and reconstruction data does not differ significantly
      Notes: The heart of the question is twofold: 1) can we adjust the micrometer to penetrate the support polymer and still measure the object in the center and 2) does the polymer cause light diffusion to the point of damaging our measurement - I have only addressed #2 here. 


** Shuyen
*** Harness frame strength
    + Importance :: good to know that it’s strong, meeting robustness
                    EDS
    + Purpose :: making sure the frame is strong enough to hold things
                 in place
    + Functionality :: Probably related to robustness – things must
                       survive some amount of force
**** Protocol
     subject individual pieces to different loading
     1. tensile and bending
     2. Take one piece; hold it in place with clamp(s)
     3. Load weight on it: 30g, 50g, 100g, 300g, (1kg?) at different
        position
     4. Change the orientation of the piece and load again
     5. Repeat for different pieces
**** Results
     + Test metrics 
       1. Orientation of piece
       2. Amount of weight loaded, 
       3. Position of loading
       4. Breaking (y/n)
     + Possible results 
       + Good :: no breaking
       + Bad :: anything breaks

*** Harness frame assembly failure
    + Importance :: meeting EDS
    + Purpose :: To verify the specification of ability to sustain
                 3-ft drop impact
    + Functionality :: see above
**** Protocol
     1. Assemble frame structure onto base
     2. Drop the assembly from 3-ft height to concrete floor
     3. Examine frame for any material failure (i.e. fracture,
        breaking) or detachment from base or from each other
     4. Repeat several (5-10?) times and record the number of repeat
        and the result of each repeat
**** Results
     + Test metrics
       1. number of repeat (values are from 1-10)
       2. Fracture (y/n)
       3. Breaking (y/n)
       4. Detachment from base (y/n)
       5. Loose connection between frame pieces (y/n) 
     + Possible test results
       + Good result :: all the y/n question receives an “n” (no
                        fracture, breaking, detachment etc)
       + Bad result :: any fracture, breaking, detachment

*** Harness frame stiffness
    + Importance :: meeting stability EDS
    + Purpose :: make sure the frame can hold things in their relative
                 position without much deviation
    + Functionality :: probably related to stability and accurate
                       measurement – things need to be in the right
                       places and not move too much
**** Protocol
    + For Individual components ::
    (see harness frame strength test)
    + Note significant bending (visible to the eye, y/n)
    + Measure deflection distance, also record bending direction
    + For Assembly: 
    + Mark the test tube black with dry-erase marker
    + Assemble the frame harness and core piece (testtube and caps)
    + Measure the test tube with the micrometer at low angular speed (assumption: low angular speed will not cause large force on the frame and in turn create deflection in the frame pieces)
    + Measure the test tube with the micrometer at high speed again
    + Compare the data set obtained at different angular speed
**** Results
     + Test metrics ::
       for Individual components
       (same as frame strength test)
       1. Significant bending (y/n)
       2. Deflection (length unit)
       for assembly ::
       1. angular speed
       2. measurement data set
     + Possible results
       + for individual components
       + Good :: no significant bending at all
       + Bad :: Significant bending, especially at low weight (low
                force)
       + for assembly
       + Good :: small/statistically insignificant difference between the measurement data at different angular speed
       + Bad :: opposite of good
*** Thermal expansion test
    + Importance :: good to know? May need to meet EDS
    + Purpose :: to verify that the device will work in the
                 temperature range of 22±5 °C
    + Functionality :: structural integrity at room temperature
**** Protocol
     1. Assemble the device at 17 °C
     2. Heat the device up to 27 °C (use a convection incubator or
        something)
     3. Examine device for fracture  
     4. Assemble the device at 27°C
     5. Cool it down to 17°C (refrigerator?)
     6. Examine device for loose connection or detachment
**** Results
     + Test Metrics
       1. fracture with increased T (y/n)
       2. Loose connection with decreased T (y/n)
     + Possible results
       + Good :: no fracture or loose parts
       + Bad :: fracture/loose parts, or not able to assemble when
                temperature is higher
** Sanjay
*** Data Input/Output
    + Importance :: To check whether or not the system is setup such
                    that data is properly streaming in from the
                    micrometer, motors, and encoders to the
                    computer. If there is a data I/O error, then the
                    device won't function properly!
    + Purpose :: To verify that the physical and software setup on for
                 the I/O is properly done, meaning that data from the
                 encoders and the micrometer is properly streaming in,
                 and that the digital pulses to drive the motors are
                 properly reaching the motors.
**** Protocol
     1. Fully connect and power the device (all motors and encoders
        are connected and powered; the micrometer is connected and
        powered; the NI hardware is powered and connected to the
        device and to a computer)
     2. Load an object of known dimension (eg: sphere) into the
        device.
     2. Record the distance measured by the micrometer by reading from
        the digital I/O lines which encode the distance. Update the
        measurement every time the latch digital line on the
        micrometer activates, indicating an updated measured value.
     3. Record from the encoder attached to the z-motor
     4. Send out a digital pulse train to the motor controlling the
        z-direction movement of the micrometer. 
     5. Stop digital pulse train to the z-motor after a set number
        (eg: 1000) of ticks have been recorded by the encoder attached
        to the z-motor
     6. Record from the encoder attached to the rotational motor
     7. Send out a digital pulse to the motor controlling the rotation
        of the eyeball/test tube
     8. Stop digital pulse train to the rotational motor after a set
        number (eg: 1000) of ticks have been recorded by the encoder
        attached to the rotational motor. 
     9. Send out a digital pulse to both the z-motor and the
        rotational motor.
     10. Record from both encoders -- the one attached to the z-motor,
         and the one attached to the rotational motor. 
     11. Stop output to the motors, and stop input from the encoders
         and the micrometer. 
**** Results
     + Test Metrics
       1. Did the decoded input from the micrometer correspond with
          the reading on the screen?
       2. Did the z-motor move at a proper rate and the proper amount
          when engaged with a digital pulse?
       3. Did the rotational motor move at a proper rate and the
          proper amount when engaged with a digital pulse?
       4. Did the movment of the two motors correspond with the
          readout from the encoders when activated simultaneously?
       5. Did the decoded signal from the micrometer correspond with
          the readout on the screen during both single and
          simultaneous activation of the motors and encoders?
     + Possible Results
       1. Yes to Metric 1 indicates that the data was being properly
          sent down the digital lines to the NI board and was being
          decoded properly
       2. For Metric number 2 and 3, if the motor moved at the proper
          rate (correleating with the specifications/calibration of
          the motor), it means that the motor didn't slip, and that
          the digital output to the motor is properly functioning. If
          the encoder ticks didn't correspond to the motor distance,
          it indicates that the encoder failed to propery record the
          movement of the motor. If the motors didn't move at all, it
          indicates a failure in the digital output to the motor, and
          if the encoder failed to record any movment, it indicates a
          failure in the setup of the encoder.
       3. For Metric 4, if the movement of the two motors corresponded
          to the encoder readings, it indicates successful
          simultaneous activation of the motor control system. If
          there is a discrepency between the movement of the motors
          and the readout from the encoder, it indicates an
          unsuccessful simultaneous activation of the motor control system.
       4. For Metric 5, if the decoded signal corresponded with the
          readout on the screen, it indicates successful simultaneous
          activation of the micrometer with the motor system. If the
          decoded signal failed to match the readout on the screen, it
          indicates that the micrometer and motor control system fail
          to work properly in parallel.
*** Reconstruction Algorithm
    + Importance :: The reconstruction algorithm is key to moving from
                    raw data to useable information. Without
                    generating a proper reconstruction, the device
                    would be useless as a tool for scientific
                    investigation.
    + Purpose :: To verify that the reconstruction algorithm properly
                 converts from raw data to a 3-D rendering of the test
                 sample.
**** Protocol
     1. Generate an artificial data set which contains no noise,
        and encodes the measurements for an object of pre-determined
        dimension (aka a sphere of set radius)
     2. Input artificial data into the reconstruction algorithm
     3. Check the output of the reconstruction algorithm against the
        object defined by the input data
**** Results
     + Test Metric
       1. Did the reconstruction (output from the reconstruction
          algorithm) match the original object defined by the
          generated data?
     + Possible Results
       1. The reconstruction (output) matches the object defined by
          the raw data input, meaning that the reconstruction
          algorithm is fuctioning properly. If the output doesn't
          match the input, it indicates an error in the reconstruction
          algorithm.



